removeEmoji()
elvanto/litemoji pull request #28
Opened 2021-11-17 23:36 UTC by KarelWintersky

* [+] added ext-mbstring dependency to composer.json
* [+] added static method `removeEmoji()`
* [+] added test method `testRemoveEmoji()`, test passed
* [*] callback declared as `static function` instead of `function

2021-11-17 23:40 UTC, KarelWintersky commented
Also, I think, we can add file `.gitattributes`:

```
* text=auto
* eol=lf

.git				export-ignore
.gitattributes      export-ignore
.gitignore          export-ignore
.github             export-ignore
tests               export-ignore
vendor              export-ignore
phpunit.xml         export-ignore
bin                 export-ignore
```
tests and generate scripts can be removed from exported package, 'cause tests and `shortcodes-array.php` required at development stage.

2021-11-18 04:01 UTC, joshmcrae requested changes
Thanks for this enhancement! A couple of minor changes to make before continuing but other than those I'm happy to merge and release.

The `.gitattributes` change looks acceptable too.

2021-11-18 09:25 UTC, KarelWintersky commented on src/LitEmoji.php
> +    public static function removeEmoji(string $source):string
fixed

2021-11-18 09:26 UTC, KarelWintersky commented on tests/LitEmojiTest.php
> +        $this->assertEquals('Some text  including emoji ', $text); //NB: smile emoji surrounded with TWO spaces.
fixed

2021-11-18 09:27 UTC, KarelWintersky commented
gitattributes added

2021-11-18 22:20 UTC, joshmcrae approved these changes

2021-11-18 22:21 UTC, merged

2021-11-18 22:23 UTC, joshmcrae commented
Released as [4.1.0](https://github.com/elvanto/litemoji/releases/tag/4.1.0).